#!/bin/bash
#SBATCH -J new_200k_0p9
#SBATCH -A KRUEGER-SL2-GPU
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --time=36:00:00
#SBATCH --mail-type=ALL
#SBATCH -p ampere
#. /etc/profile.d/modules.sh
#module purge
#module load rhel8/default-amp
module load python/3.8
source ../pytorch-env/bin/activate
#python make_dataset_balanced.py --train_data_path './saved_data/basic_all_same_50L1_train_dataset_new.pkl'  --val_data_path './saved_data/basic_all_same_50L1_val_dataset_new.pkl'  --test_data_path './saved_data/basic_all_same_50L1_test_dataset_new.pkl' --num_samples_train 5000000

export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python pretrain_mod.py --path_load_train_data ./saved_data/basic_50k_train_uniform.pkl --path_load_val_data ./saved_data/basic_50k_val_uniform.pkl --path_load_test_data ./saved_data/basic_50k_test_uniform.pkl --wandb-project "dgp-pretrain-count-newsetup-uniform" --O2_token_task_count 40 --wandb-run 'mini_pe_enc_O1_a_new_200k_0p9_CS_prob_0p75_others_same_schedule_2k_8k_lr1em3' --max_iters 200000 --learning_rate 1e-3 --warmup_iters 20000  --lr_decay_iters 180000 --save_path 'checkpoints_mini_pe_enc_uniform_O1_a_new_200k_0p9_CS_prob_0p75_others_same_schedule_2k_8k_lr_1em3' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 0.9 --O1_sample_weight_b 0.1 --O1_sample_weight_c 0.0 --O1_sample_weight_a_test 0.33 --O1_sample_weight_b_test 0.33  --O1_sample_weight_c_test 0.33 --prob_CS 0.2 --prob_CD 0.2 --prob_IS 0.2 --prob_ID 0.2 --prob_F 0.2  --prob_CS_val 0.2 --prob_CD_val 0.2 --prob_IS_val 0.2 --prob_ID_val 0.2 --prob_F_val 0.2 --prob_CS_test 0.2 --prob_CD_test 0.2 --prob_IS_test 0.2 --prob_ID_test 0.2 --prob_F_test 0.2 | tee -a logs/mini_pe_enc_O1_a_new_200k_0p9_CS_prob_0p75_others_same_schedule_2k_8k_lr_1em3.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 1.0 --pretrained_model_path './pretrained_models/checkpoints_mini_pe_enc_uniform_O1_a_new_200k_0p9_CS_prob_0p75_others_same_schedule_2k_8k_lr_1em3/model_200000.pkl' --wandb-run 'mini_pe_enc_new_200k_0p9_SpT1p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT1p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/mini_pe_enc_new_200k_0p9_SpT1p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.0 --pretrained_model_path './pretrained_models/checkpoints_mini_pe_enc_uniform_O1_a_new_200k_0p9_CS_prob_0p75_others_same_schedule_2k_8k_lr_1em3/model_200000.pkl' --wandb-run 'mini_pe_enc_new_200k_0p9_SpT0p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/mini_pe_enc_new_200k_0p9_SpT0p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.5 --pretrained_model_path './pretrained_models/checkpoints_mini_pe_enc_uniform_O1_a_new_200k_0p9_CS_prob_0p75_others_same_schedule_2k_8k_lr_1em3/model_200000.pkl' --wandb-run 'mini_pe_enc_new_200k_0p9_SpT0p5_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p5_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/mini_pe_enc_new_200k_0p9_SpT0p5_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.8 --pretrained_model_path './pretrained_models/checkpoints_mini_pe_enc_uniform_O1_a_new_200k_0p9_CS_prob_0p75_others_same_schedule_2k_8k_lr_1em3/model_200000.pkl' --wandb-run 'mini_pe_enc_new_200k_0p9_SpT0p8_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p8_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/mini_pe_enc_new_200k_0p9_SpT0p8_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt

export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.75 --pretrained_model_path './pretrained_models/checkpoints_mini_pe_enc_uniform_O1_a_new_200k_0p9_CS_prob_0p75_others_same_schedule_2k_8k_lr_1em3/model_200000.pkl' --wandb-run 'mini_pe_enc_new_200k_0p9_SpT0p75_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p75_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/mini_pe_enc_new_200k_0p9_SpT0p75_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.9 --pretrained_model_path './pretrained_models/checkpoints_mini_pe_enc_uniform_O1_a_new_200k_0p9_CS_prob_0p75_others_same_schedule_2k_8k_lr_1em3/model_200000.pkl' --wandb-run 'mini_pe_enc_new_200k_0p9_SpT0p9_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p9_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/mini_pe_enc_new_200k_0p9_SpT0p75_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt

export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.0   --y_label 'a' --y_label_dup 'b' --original_label 'b' --pretrained_model_path './finetuned_models/checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune/model_10000.pkl' --wandb-run 'reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p5_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.0   --y_label 'a' --y_label_dup 'b' --original_label 'b' --pretrained_model_path './finetuned_models/checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p5_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune/model_10000.pkl' --wandb-run 'reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p5_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p5_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p5_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.0   --y_label 'a' --y_label_dup 'b' --original_label 'b' --pretrained_model_path './finetuned_models/checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p8_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune/model_10000.pkl' --wandb-run 'reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p8_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p8_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p8_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.0   --y_label 'a' --y_label_dup 'b' --original_label 'b' --pretrained_model_path './finetuned_models/checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p75_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune/model_10000.pkl' --wandb-run 'reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p75_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p75_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p75_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.0   --y_label 'a' --y_label_dup 'b' --original_label 'b' --pretrained_model_path './finetuned_models/checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT0p9_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune/model_10000.pkl' --wandb-run 'reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p9_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p9_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p99_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt
export WANDB_API_KEY=20ad82078ee09233a64fbf43afd2fdef565048a2
python finetune_mod.py --path_load_train_data2 ./saved_data/basic_10k_train_SC1p0_count_uniform.pkl --path_load_val_data2 ./saved_data/basic_10k_val_SC1p0_count_uniform.pkl --path_load_test_data2 ./saved_data/basic_10k_test_SC1p0_count_uniform.pkl --path_load_train_data ./saved_data/basic_10k_train_uniform.pkl --path_load_val_data ./saved_data/basic_10k_val_uniform.pkl --path_load_test_data ./saved_data/basic_10k_test_uniform.pkl --wandb-project "dgp-finetune-count-newsetup-uniform" --spurious_correlation_train 0.0   --y_label 'a' --y_label_dup 'b' --original_label 'b' --pretrained_model_path './finetuned_models/checkpoints_mini_pe_enc_uniform_new_200k_0p9_SpT1p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune/model_10000.pkl' --wandb-run 'reverse_mini_pe_enc_uniform_new_200k_0p9_SpT1p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --max_iters 10000 --warmup_iters 2000  --lr_decay_iters 8000 --save_path 'checkpoints_reverse_mini_pe_enc_uniform_new_200k_0p9_SpT1p0_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune' --embedding_type 'pe' --model_type 'wrn2-cfg-mini' --O1_sample_weight_a 1 --O1_sample_weight_b 11.0 --O1_sample_weight_a_test 0.0 --O1_sample_weight_b_test 1.0 --prob_CS 1.0 --prob_CD 0.0 --prob_IS 0.0 --prob_ID 0.0 --prob_F 0.0  --prob_CS_val 1.0 --prob_CD_val 0.0 --prob_IS_val 0.0 --prob_ID_val 0.0 --prob_F_val 0.0 --prob_CS_test 1.0 --prob_CD_test 0.0 --prob_IS_test 0.0 --prob_ID_test 0.0 --prob_F_test 0.0 | tee -a logs_finetune/reverse_mini_pe_enc_uniform_new_200k_0p9_SpT0p99_finetune_b_pretrain_a_CS_prob_0p75_pretraining_others_same_schedule_2k_8k_finetune.txt

