#!/bin/bash

CUDA_VISIBLE_DEVICES=1 python acc_lmc_analysis_new.py --plot_path 'ssft_1em5' --data_test 'std_unsafe' --model_load_path './transferred_models/ssft_1em5/model_500.pkl'  --learning_rate 0.00005 --min_lr 0.0000005 --model_type 'wrn2-cfg-mini'   --wandb-project 'attention_maps'  --max_input_length 35  --max_window_possible 159 --max_iters 10000 --max_train_iters 10000 --warmup_iters 2000 --lr_decay_iters 8000 --prob_safe 0.0 --prob_unsafe 1.0 --safe_branch_prob 0.5 --id_mg_prob 0.5 --is_dpo 0 --dpo_weight_safe 0 --dpo_weight_unsafe 0  --save_path 'attention' --wandb-run 'attention'
CUDA_VISIBLE_DEVICES=1 python acc_lmc_analysis_new.py --plot_path 'ssft_1em5' --data_test 'std_safe' --model_load_path './transferred_models/ssft_1em5/model_500.pkl'  --learning_rate 0.00005 --min_lr 0.0000005 --model_type 'wrn2-cfg-mini'   --wandb-project 'attention_maps'  --max_input_length 35  --max_window_possible 159 --max_iters 10000 --max_train_iters 10000 --warmup_iters 2000 --lr_decay_iters 8000 --prob_safe 0.0 --prob_unsafe 1.0 --safe_branch_prob 0.5 --id_mg_prob 0.5 --is_dpo 0 --dpo_weight_safe 0 --dpo_weight_unsafe 0  --save_path 'attention' --wandb-run 'attention'
# CUDA_VISIBLE_DEVICES=1 python model_analysis_lmc_theta_act_all_activation_rotation_analysis_new_transform_new.py --num 200 --plot_path 'ssft_1em5' --data_test 'std_unsafe' --model_load_path './transferred_models/ssft_1em5/model_200.pkl'  --learning_rate 0.00005 --min_lr 0.0000005 --model_type 'wrn2-cfg-mini'   --wandb-project 'attention_maps'  --max_input_length 35  --max_window_possible 159 --max_iters 10000 --max_train_iters 10000 --warmup_iters 2000 --lr_decay_iters 8000 --prob_safe 0.0 --prob_unsafe 1.0 --safe_branch_prob 0.5 --id_mg_prob 0.5 --is_dpo 0 --dpo_weight_safe 0 --dpo_weight_unsafe 0  --save_path 'attention' --wandb-run 'attention'
# CUDA_VISIBLE_DEVICES=1 python model_analysis_lmc_theta_act_all_activation_rotation_analysis_new_transform_new.py --num 500 --plot_path 'ssft_1em5' --data_test 'std_unsafe' --model_load_path './transferred_models/ssft_1em5/model_500.pkl'  --learning_rate 0.00005 --min_lr 0.0000005 --model_type 'wrn2-cfg-mini'   --wandb-project 'attention_maps'  --max_input_length 35  --max_window_possible 159 --max_iters 10000 --max_train_iters 10000 --warmup_iters 2000 --lr_decay_iters 8000 --prob_safe 0.0 --prob_unsafe 1.0 --safe_branch_prob 0.5 --id_mg_prob 0.5 --is_dpo 0 --dpo_weight_safe 0 --dpo_weight_unsafe 0  --save_path 'attention' --wandb-run 'attention'
# CUDA_VISIBLE_DEVICES=1 python model_analysis_lmc_theta_act_all_activation_rotation_analysis_new_transform_new.py --num 1000 --plot_path 'ssft_1em5' --data_test 'std_unsafe' --model_load_path './transferred_models/ssft_1em5/model_1000.pkl'  --learning_rate 0.00005 --min_lr 0.0000005 --model_type 'wrn2-cfg-mini'   --wandb-project 'attention_maps'  --max_input_length 35  --max_window_possible 159 --max_iters 10000 --max_train_iters 10000 --warmup_iters 2000 --lr_decay_iters 8000 --prob_safe 0.0 --prob_unsafe 1.0 --safe_branch_prob 0.5 --id_mg_prob 0.5 --is_dpo 0 --dpo_weight_safe 0 --dpo_weight_unsafe 0  --save_path 'attention' --wandb-run 'attention'
# CUDA_VISIBLE_DEVICES=1 python model_analysis_lmc_theta_act_all_activation_rotation_analysis_new_transform_new.py --num 2000 --plot_path 'ssft_1em5' --data_test 'std_unsafe' --model_load_path './transferred_models/ssft_1em5/model_2000.pkl'  --learning_rate 0.00005 --min_lr 0.0000005 --model_type 'wrn2-cfg-mini'   --wandb-project 'attention_maps'  --max_input_length 35  --max_window_possible 159 --max_iters 10000 --max_train_iters 10000 --warmup_iters 2000 --lr_decay_iters 8000 --prob_safe 0.0 --prob_unsafe 1.0 --safe_branch_prob 0.5 --id_mg_prob 0.5 --is_dpo 0 --dpo_weight_safe 0 --dpo_weight_unsafe 0  --save_path 'attention' --wandb-run 'attention'
# CUDA_VISIBLE_DEVICES=1 python model_analysis_lmc_theta_act_all_activation_rotation_analysis_new_transform_new.py --num 5000 --plot_path 'ssft_1em5' --data_test 'std_unsafe' --model_load_path './transferred_models/ssft_1em5/model_5000.pkl'  --learning_rate 0.00005 --min_lr 0.0000005 --model_type 'wrn2-cfg-mini'   --wandb-project 'attention_maps'  --max_input_length 35  --max_window_possible 159 --max_iters 10000 --max_train_iters 10000 --warmup_iters 2000 --lr_decay_iters 8000 --prob_safe 0.0 --prob_unsafe 1.0 --safe_branch_prob 0.5 --id_mg_prob 0.5 --is_dpo 0 --dpo_weight_safe 0 --dpo_weight_unsafe 0  --save_path 'attention' --wandb-run 'attention'
# CUDA_VISIBLE_DEVICES=1 python model_analysis_lmc_theta_act_all_activation_rotation_analysis_new_transform_new.py --num 1000 --plot_path 'ssft_1em5' --data_test 'std_unsafe' --model_load_path './transferred_models/ssft_1em5/model_10000.pkl'  --learning_rate 0.00005 --min_lr 0.0000005 --model_type 'wrn2-cfg-mini'   --wandb-project 'attention_maps'  --max_input_length 35  --max_window_possible 159 --max_iters 10000 --max_train_iters 10000 --warmup_iters 2000 --lr_decay_iters 8000 --prob_safe 0.0 --prob_unsafe 1.0 --safe_branch_prob 0.5 --id_mg_prob 0.5 --is_dpo 0 --dpo_weight_safe 0 --dpo_weight_unsafe 0  --save_path 'attention' --wandb-run 'attention'
